MocuGame = {};
MocuGame.preload = new createjs.LoadQueue();
MocuGame.imageManifest = [{ id: "Background", src: "images/Background.png" },
{ id: "BG1Layer1", src: "images/BG1Layer1.png" },
{ id: "BG1Layer2", src: "images/BG1Layer2.png" },
{ id: "BG1Layer3", src: "images/BG1Layer3.png" },
{ id: "BG1Layer4", src: "images/BG1Layer4.png" },
{ id: "BG1Layer5", src: "images/BG1Layer5.png" },
{ id: "BG2Layer1", src: "images/BG2Layer1.png" },
{ id: "BG2Layer2", src: "images/BG2Layer2.png" },
{ id: "BG2Layer3", src: "images/BG2Layer3.png" },
{ id: "BG2Layer4", src: "images/BG2Layer4.png" },
{ id: "BG2Layer5", src: "images/BG2Layer5.png" },
{ id: "Dekplane", src: "images/Dekplane.png" },
{ id: "Dekta1Body", src: "images/Dekta1Body.png" },
{ id: "Dekta1Chain", src: "images/Dekta1Chain.png" },
{ id: "Dekta1Gun", src: "images/Dekta1Gun.png" },
{ id: "Dekta1Shard1", src: "images/Dekta1Shard1.png" },
{ id: "Dekta1Shard2", src: "images/Dekta1Shard2.png" },
{ id: "Dekta1Shard3", src: "images/Dekta1Shard3.png" },
{ id: "Dilo", src: "images/Dilo.png" },
{ id: "Dudekplane", src: "images/Dudekplane.png" },
{ id: "Duspinfodder", src: "images/Duspinfodder.png" },
{ id: "Dusquilo", src: "images/Dusquilo.png" },
{ id: "EnemyBullet1", src: "images/EnemyBullet1.png" },
{ id: "EnemyBullet2", src: "images/EnemyBullet2.png" },
{ id: "Fire", src: "images/Fire.png" },
{ id: "HitParticle1", src: "images/HitParticle1.png" },
{ id: "HitParticle2", src: "images/HitParticle2.png" },
{ id: "HUDBombHolder", src: "images/HUDBombHolder.png" },
{ id: "HUDBombHolder_Fill", src: "images/HUDBombHolder_Fill.png" },
{ id: "Lo", src: "images/Lo.png" },
{ id: "logo", src: "images/logo.png" },
{ id: "logo", src: "images/logo.scale-100.png" },
{ id: "logo", src: "images/logo.scale-140.png" },
{ id: "logosmall", src: "images/logosmall.png" },
{ id: "logosmall", src: "images/logosmall.scale-100.png" },
{ id: "logosmall", src: "images/logosmall.scale-140.png" },
{ id: "logosmall150", src: "images/logosmall150.png" },
{ id: "logowide", src: "images/logowide.png" },
{ id: "ModularSnakeBody", src: "images/ModularSnakeBody.png" },
{ id: "ModularSnakeHead", src: "images/ModularSnakeHead.png" },
{ id: "Plano", src: "images/Plano.png" },
{ id: "ringparticle1", src: "images/ringparticle1.png" },
{ id: "SandiscBlade", src: "images/SandiscBlade.png" },
{ id: "SandiscBody", src: "images/SandiscBody.png" },
{ id: "SandiscOrb", src: "images/SandiscOrb.png" },
{ id: "SandiscPreview", src: "images/SandiscPreview.png" },
{ id: "Shrio Bomb Boom", src: "images/Shrio Bomb Boom.png" },
{ id: "Shrio Bomb", src: "images/Shrio Bomb.png" },
{ id: "Shrio Title Logo", src: "images/Shrio Title Logo.png" },
{ id: "ShrioBullet", src: "images/ShrioBullet.png" },
{ id: "ShrioLogo", src: "images/ShrioLogo.png" },
{ id: "ShrioSheet", src: "images/ShrioSheet.png" },
{ id: "smallestlogo", src: "images/smallestlogo.png" },
{ id: "smalllogo", src: "images/smalllogo.png" },
{ id: "Spinfodder", src: "images/Spinfodder.png" },
{ id: "splashscreen", src: "images/splashscreen.png" },
{ id: "Squilo", src: "images/Squilo.png" },
{ id: "storelogo", src: "images/storelogo.png" }];
MocuGame.soundManifest = [];
MocuGame.musicManifest = [{ id: "Level1", src: "music/Level1.mp3" },
{ id: "Title", src: "music/Title.mp3" }];

MocuGame.onLoaded = function () { console.log("Resources loaded"); }
MocuGame.currentMusic = null;